<a href="https://colab.research.google.com/github/alexmal2804/hwds/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22HW_7_lesson_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Решения задач в конце ноутбука

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

##Задача № 2. Решение
1. Найти сумму матриц:
 $С=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $+ \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $=\begin{pmatrix}
1+4 & -2-1\\
3 & 5
\end{pmatrix}$ $=\begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}$

In [2]:
#Проверка с исп. Numpy операции сложения матриц
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
C = A + B
print(f'Сумма матриц равна\n {C}.\n')

Сумма матриц равна
 [[ 5 -3]
 [ 3  5]].



2. Найти произведение  матриц:
 $D=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $* \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $=\begin{pmatrix}
4-0 & -1-10\\
12+0 & -3+0
\end{pmatrix}$ $=\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}$

In [3]:
#Проверка с исп. Numpy операции умножения матриц
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
D = np.dot(A, B)
print(f'Произведение матриц равно\n {D}.\n')

Произведение матриц равно
 [[  4 -11]
 [ 12  -3]].



##Задача № 3. Решение
Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$D= 3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ $ - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ $ + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} $=

$= \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ $ + \begin{pmatrix}
0 & 10\\ 
-4 & 2
\end{pmatrix}$ $ + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} $ $= \begin{pmatrix}
8 & 11\\ 
5 & -16
\end{pmatrix}$ $ + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} $ $= \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

In [4]:
#Проверка с исп. Numpy линейной комбинации матриц
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
D = 3 * A -2 * B + 4 * C
print(f'Линейная коминация матриц равна\n {D}.\n')

Линейная коминация матриц равна
 [[ 11  -5]
 [  9 -12]].



##Задача № 4. Решение
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


 $A^{T} = =\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

$A \cdot A^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ $\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$= $\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9\\
\end{pmatrix}$=$\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\
\end{pmatrix}.$


$A^{T} \cdot A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$ $\cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ = $\begin{pmatrix}
16+25+4 & 4-10+6 \\ 
4-10+6 & 1+4+9 \\ 
\end{pmatrix}$=$\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\ 
\end{pmatrix}.$

In [5]:
#Проверка с исп. Numpy
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
B = np.dot(A, AT)
C = np.dot(AT, A)
print(f'A * AT = \n {B}.\n')
print(f'AT * A = \n {C}.\n')

A * AT = 
 [[17 18 11]
 [18 29  4]
 [11  4 13]].

AT * A = 
 [[45  0]
 [ 0 14]].



##Задача № 5*. Решение
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def dot_matrix(a : list, b: list):
  


##Задача № 6. Решение
Вычислить определитель:

   a)   $det=\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^{2}x+cos^{2}x=1.$

   б) $det=\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=8 \cdot (45 - 0) - 4 \cdot (0 - 0) +6 \cdot (0-0) = 360,$

или $det=\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}= 8 \cdot 5 \cdot 9 = 360$, т.к. для треугольной матрицы определитель равен произведению элементов главной диагонали.
    
   в) $det = \begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}=2 \cdot (60-63) - 3 \cdot (50-56) +6 \cdot (45-48) = -6 + 18 -12 =0.$

In [12]:
# 1) Проверка с исп. Numpy
import math
x = math.pi/4
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
print(f'a) определитель: {np.linalg.det(A):.0f}')

a) определитель: 1


In [13]:
# 2)Проверка с исп. Numpy
B = np.array([[8, 4, 6], [0, 5, 1], [0, 0, 9]])
print(f'a) определитель: {np.linalg.det(B):.0f}')

a) определитель: 360


In [14]:
# 3)Проверка с исп. Numpy
C = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(f'a) определитель: {np.linalg.det(C):.0f}')

a) определитель: 0


##Задача 7. Решение 
Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$:

   $det(A^{2}) = 4 \cdot 4 = 16$,

   т.к. по свойству 9 определителей для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB.$ Следовательно $det(A \cdot A)=detA\cdot detA.$
 
   б) $det(A^{T})$:

   $det(A^{T}) = det(A) = 4$,

   т.к. по первому свойсту определителей определитель транспонированной матрицы равен определителю исходной.
    
   в) $det(2A)$:

   $det(2A) = 8$,
  
  т.к. по второму свойству определителей умножение строки или столбца матрицы на число  приведет к умножению определителя матрицы на то же число.
   

In [34]:
A = np.array([[1, 2, 3], [0, 2, 4], [0, 0, 2]])
print(f'определитель матрицы А равен: {np.linalg.det(A):.0f}')
print(f'определитель транспонированной матрицы равен: {np.linalg.det(A.T):.0f}')
print(f'определитель матрицы 2*А равен: {np.linalg.det(2*A):.0f}')

определитель матрицы А равен: 4
определитель транспонированной матрицы равен: 4
определитель матрицы 2*А равен: 32
