<a href="https://colab.research.google.com/github/alexmal2804/hwds/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22HW_7_lesson_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/drive/15yZEp6Fig3goSVv_t3hL30ZUHgazuauh?usp=sharing

#Решения задач в конце ноутбука

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [218]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

#Задача № 1. 
Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

  - Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

#Решение:
Косинусовое подобие используется в задачах машинного обучения для сравнения нескольких (в простейшем случае двух) наборов признаков. В случае, когда мы не учитываем сходства между элементами векторов, то находим подобие в ортогональном базисе и  задача сводится к нахождению косинуса угла между векторами, который равен отношению скалярного произведения векторов к произведению норм $l^2$ этих векторов:
$$cos (a, b) =\frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\|\|\vec{b}\|}=\frac{\sum_{1}^{n} a_{i} b_{i}}{\sqrt{\sum_{1}^{n} a_{i}^{2}} \sqrt{\sum_{1}^{n} b_{i}^{2}}} \verb|  (1)|
$$  

При этом не берется в расчет возможное сходство между каждым из элементов сравниваемых векторов и, в том случае, если это сходство необходимо учитывать - построенная с использованием обычного косинусового подобия модель может быть неточной, т.к. не будет отражать значимые соответветствия между объектами (признаками). Самый простой для понимания пример - это попытка семантического сравнения двух текстов на одну тематику на естественном языке, которая не учитывает синонимов, похожих по смыслу словосочетаний и т.п. Очевидно, что результат в невырожденном случае не будет нас устраивать.

Когда есть возможность построить таблицу сходства признаков $c_{i,j}$, то для сравнения векторов может использоваться мягкое косинусовое подобие, которое можно рассчитать по формуле (вывод формулы приводится в http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf):
$$\verb|soft_cousine| (a, b) =\frac{\sum_{i,j}^{n} s_{i,j} a_{i} b_{j}}{\sqrt{\sum_{i,j}^{n} s_{i,j} a_{i} a_{j}} \cdot \sqrt{\sum_{i,j}^{n} s_{i,j} b_{i} b_{j}}}
\verb|  (2)|
$$
Если сходства между элементами векторов нет, то выражение (2) будет эквивалентно (1).

При этом сложность  мягкого косинусового подобия является квадратичной и позволяет вполне эффективно использовать его для решения вычислительных задач с большим количеством элементов в векторе (есть  методы оптимизации метода, но в рамках решения этой задачи мы их рассматривать не будем). Ниже приведен пример сравнения  двух целочисленных векторов одинаковой длины, которое учитывает мат.порядок сравниваемых числовых элементов, с решением на Python.

In [219]:
# Пример решения задачи с использованием мягкого косинусового подобия
# Даны два вектора одинаковой размерности  с целочисленными элементами.
# Найти мягкое косинусовое подобие этих матриц с учетом различия в порядках чисел, составляющих элементы матрицы
a = np.array([10, 234, 145, 12, 1237, 8, 24562, 123, 23, 1])
b = np.array([127, 4, 789823, 486, 0, 12, 77, 192, 555, 1234567890, 21])
c1 = np.array([127, 4, 789823, 486, 0, 12, 77, 192, 555, 1234567890])

In [220]:
# Построим таблицу сходства признаков
def similarity_signs(a : np.array, b : np.array):
  if len(a) != len(b):
    return 'Данная функция определяет подобие только для векторов одинаковой размерности'
  # Построим таблицу сходства признаков
  n = len(a)
  s = np.zeros([n, n], dtype = float) 
  for i in range(n):
    for j in range(n):
      # сравниваем отношение порядков каждого из элмента числового вектора и в качестве критерия сходства берем отношение меньшего к большему 
      sa = len(str(a[i]))
      sb = len(str(b[j]))
      s[i, j] = sb / sa if sa > sb else sa / sb
  return s
  

In [221]:
import math
# Найдем мягкое косинусовое подобие
def soft_cousine(a : np.array, b : np.array):
  if len(a) != len(b):
    return 'Данная функция определяет подобие только для векторов одинаковой размерности'
  # Если размерность векторов совпадает, определяем подобие
  n = len(a)
  s = similarity_signs(a, b)
  s_cos = 0
  norm_a = 0
  norm_b = 0
  for i in range(n):
    for j in range(n):
      s_cos += s[i,j] * a[i] * b[j]
      norm_a += s[i,j] * a[i] * a[j]
      norm_b += s[i,j] * b[i] * b[j]
  return s_cos/(math.sqrt(norm_a) * math.sqrt(norm_b))


In [222]:
# Найдем мягкое косинусовое подобие
# Построение таблицы сходства признаков (демонстрация работы функции, которая используется как вложенная в soft_cousine)
# print(f'Таблица сходства признаков векторов\n {a}\n и\n {c1}\n выглядит так:\n {similarity_signs(a, c1)}')
# Векторы разной размерности не будут обработаны этой функцией
print(f'Для векторов разной размерности:\n {soft_cousine(a, b)}')
# Для векторов одинаковой размерности будет определено мягкое косинусовое подобие
print(f'Для векторов одинаковой размерности:\n {soft_cousine(a, c1)}')

Для векторов разной размерности:
 Данная функция определяет подобие только для векторов одинаковой размерности
Для векторов одинаковой размерности:
 2.4442737677213673


##Задача № 2. Решение
1. Найти сумму матриц:

 $С=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $+ \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $=\begin{pmatrix}
1+4 & -2-1\\
3 & 5
\end{pmatrix}$ $=\begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}$

In [223]:
#Проверка с исп. Numpy операции сложения матриц
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
C = A + B
print(f'Сумма матриц равна\n {C}.\n')

Сумма матриц равна
 [[ 5 -3]
 [ 3  5]].



2. Найти произведение  матриц:

 $D=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $* \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $=\begin{pmatrix}
4-0 & -1-10\\
12+0 & -3+0
\end{pmatrix}$ $=\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}$

In [224]:
#Проверка с исп. Numpy операции умножения матриц
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
D = np.dot(A, B)
print(f'Произведение матриц равно\n {D}.\n')

Произведение матриц равно
 [[  4 -11]
 [ 12  -3]].



##Задача № 3. Решение
Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$D= 3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ $ - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ $ + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} $=

$= \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ $ + \begin{pmatrix}
0 & 10\\ 
-4 & 2
\end{pmatrix}$ $ + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} $ $= \begin{pmatrix}
8 & 11\\ 
5 & -16
\end{pmatrix}$ $ + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} $ $= \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

In [225]:
#Проверка с исп. Numpy линейной комбинации матриц
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
D = 3 * A -2 * B + 4 * C
print(f'Линейная коминация матриц равна\n {D}.\n')

Линейная коминация матриц равна
 [[ 11  -5]
 [  9 -12]].



##Задача № 4. Решение
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


 $A^{T} = =\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

$A \cdot A^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ $\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$= $\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9\\
\end{pmatrix}$=$\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\
\end{pmatrix}.$


$A^{T} \cdot A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$ $\cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ = $\begin{pmatrix}
16+25+4 & 4-10+6 \\ 
4-10+6 & 1+4+9 \\ 
\end{pmatrix}$=$\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\ 
\end{pmatrix}.$

In [226]:
# Проверка с исп. Numpy
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
B = np.dot(A, AT)
C = np.dot(AT, A)
print(f'A * AT = \n {B}.\n')
print(f'AT * A = \n {C}.\n')

A * AT = 
 [[17 18 11]
 [18 29  4]
 [11  4 13]].

AT * A = 
 [[45  0]
 [ 0 14]].



##Задача № 5*. Решение
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [227]:
# Умножение матрицы переданной в первом параметре на переданную во втором параметре
def dot_matrix(a : list, b: list):
  m = len(a)
  n = len(a[0])
  k = len(b[0])
  n1 = len(b)
  # проверяем на равенство кол-во столбцов в первой матрице и кол-во строк во второй
  if n != n1:
    s = 'Вычислить произведение матриц невозможно, т.к. кол-во столбцов в первой матрице (' + str(n) + ') не равно кол-ву строк второй (' + str(n1) + ').'
    return s
  c =[]
  # Производим умножение матриц 
  for i in range(0, m):
    tmp = []
    for j in range(0, k):
      dot_element = 0
      for p in range(0, n):
        dot_element += a[i][p] * b[p][j]
      tmp.append(dot_element)
    c.append(tmp)
  return c



In [228]:
# Порядок матриц позволяет найти их произведение
a = [[1, -2], [3, 0], [4, 2]]
b = [[4, -1, 3], [0, 5, -2]]
print(dot_matrix(a, b))

[[4, -11, 7], [12, -3, 9], [16, 6, 8]]


In [229]:
# Произведение матриц вычислить нельзя
a = [[1, -2], [3, 0]]
b = [[4, -1], [0, 5], [3, 5]]
print(dot_matrix(a, b))

Вычислить произведение матриц невозможно, т.к. кол-во столбцов в первой матрице (2) не равно кол-ву строк второй (3).


In [230]:
# Проверка с исп. Numpy
a = np.array([[1, -2], [3, 0], [4, 2]])
b = np.array([[4, -1, 3], [0, 5, -2]])
print(f'Результат умножения матриц\n {a.dot(b)}')

Результат умножения матриц
 [[  4 -11   7]
 [ 12  -3   9]
 [ 16   6   8]]


##Задача № 6. Решение
Вычислить определитель:

   a)   $det=\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^{2}x+cos^{2}x=1.$

   б) $det=\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=8 \cdot (45 - 0) - 4 \cdot (0 - 0) +6 \cdot (0-0) = 360,$

или $det=\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}= 8 \cdot 5 \cdot 9 = 360$, т.к. для треугольной матрицы определитель равен произведению элементов главной диагонали.
    
   в) $det = \begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}=2 \cdot (60-63) - 3 \cdot (50-56) +6 \cdot (45-48) = -6 + 18 -12 =0.$

In [231]:
# 1) Проверка с исп. Numpy
import math
x = math.pi/4
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
print(f'a) определитель: {np.linalg.det(A):.0f}')

a) определитель: 1


In [232]:
# 2)Проверка с исп. Numpy
B = np.array([[8, 4, 6], [0, 5, 1], [0, 0, 9]])
print(f'a) определитель: {np.linalg.det(B):.0f}')

a) определитель: 360


In [233]:
# 3)Проверка с исп. Numpy
C = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(f'a) определитель: {np.linalg.det(C):.0f}')

a) определитель: 0


##Задача 7. Решение 
Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$:

   $det(A^{2}) = 4 \cdot 4 = 16$,

   т.к. по свойству 9 определителей для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB.$ Следовательно $det(A \cdot A)=detA\cdot detA.$
 
   б) $det(A^{T})$:

   $det(A^{T}) = det(A) = 4$,

   т.к. по первому свойсту определителей определитель транспонированной матрицы равен определителю исходной.
    
   в) $det(2A)$:

   $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$,
  
  т.к. по второму свойству определителей умножение строки или столбца матрицы на число $\lambda$ приводит к умножению определителя матрицы на то же число. Если строк/столбцов в матрице n, и каждая умножается на скаляр $\lambda$, то определитель будет умножен на $\lambda^n.$
   

In [234]:
# Проверка
A = np.array([[1, 2, 3], [0, 2, 4], [0, 0, 2]])
print(f'определитель матрицы А равен: {np.linalg.det(A):.0f}')
print(f'определитель матрицы А*A равен: {np.linalg.det(np.dot(A,A)):.0f}')
print(f'определитель транспонированной матрицы равен: {np.linalg.det(A.T):.0f}')
print(f'определитель матрицы 2*А равен: {np.linalg.det(2*A):.0f}')

определитель матрицы А равен: 4
определитель матрицы А*A равен: 16
определитель транспонированной матрицы равен: 4
определитель матрицы 2*А равен: 32


#Задача 8.
  Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$ 

\- вырожденная.

##Доказательство:

Найдем определитель матрицы

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = -2 \cdot (-14 \cdot 13 - 7 \cdot 6) - 7 \cdot (4 \cdot 13 + 6 \cdot 3) - 3 \cdot (4 \cdot 7 - 14 \cdot 3) = 448 - 490 + 43 = 0. $

Т.к. $det = 0$ данная матрица является вырожденной (по определению).

Ч.т.д.


In [235]:
# Проверка
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'определитель матрицы А равен: {np.linalg.det(A):.0f}')

определитель матрицы А равен: 0


#Задача 9. Решение
Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} = \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$. 

Т.к. 3-я строка является суммой 1-й и 2-й - удаляем её из матрицы, затем из 1-й вычитаем вторую и меняем местами эти две строки. Ранг матрицы равен 2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2 
\end{pmatrix}=\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1 
\end{pmatrix}.$

Т.к. 3-я строка являвется суммой 1-й и 2-й - удаляем её из матрицы, затем последнюю строку ставим на место 1-й, а из 3-й вычитаем 3-ю. Ранг матрицы равен 3.

In [236]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [237]:
x = [[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]]

a = np.array(x)
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
